version: "3.8"
services:
  postgres:
    image: postgres:16.2-alpine
    container_name: some-postgres
    environment:
      - POSTGRES_PASSWORD=mysecret
    volumes:
      - ./src/db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  pgadmin:
    env_file: .env
    image: dpage/pgadmin4
    container_name: some-pgadmin
    volumes:
      - ${PWD}/servers.json:/pgadmin4/servers.json
    ports:
      - 8080:80
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
volumes:
  db-data: